<?php
/**
 * @file
 * Global fields for custom content types
 */

 /**
  * Implements hook_field_info()
  */
  function sas_archive_global_fields_field_info() {
      return array(
          'year' => array(
              'label' => t('Content Year'),
              'description' => t('Year content is about.'),
              'default_widget' => 'field_example_3text',
              'default_formatter' => 'field_example_simple_text',
          ),
        );
  }

  /**
   * Implements hook_field_validate().
   */
  function sas_archive_global_fields_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
      foreach ($items as $delta => $item) {
          if(!empty($item['year'])) {
              if (!preg_match('@[0-9]{4}', $item['year'])) {
                    $errors[$field['field_name']][$langcode][$delta][] = array(
                        'error' => 'year_invalid',
                        'message' => t('Invalid year.'),
                    );
                }
          }
      }
  }

/**
 * Implements hook_field_is_empty().
 */
function sas_archive_global_fields_field_is_empty($item, $field) {
    return empty($item['year']);
}

/**
 * Implements hook_field_formatter_info().
 */
function sas_archive_global_fields_field_formatter_info() {
    return array(
        // This formatter allows input of year as text.
        'field_example_simple_text' => array(
          'label' => t('Simple text-based formatter'),
          'field types' => array('field_year'),
        ),
      );
}

/**
 * Implements hook_field_formatter_view()
 */
function sas_archive_global_fields_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    $element = array();

    switch ($display['type']) {
        // This formatter simply outputs the field as text and with a color.
        case 'year_view':
          foreach ($items as $delta => $item) {
            $element[$delta] = array(
              '#type' => 'head_tag',
              '#tag' => 'p',
              '#value' => t('Year: @code', array('@code' => $item['year'])),
            );
          }
          break;
      }
    
      return $element;
}

/**
 * Implements hook_field_widget_info()
 */
function sas_archive_global_fields_field_widget_info() {
    return array(
        'year_widget' => array(
            'label' => t('Year value text box'),
            'field types' => array('field_year'),
          ),
    );
}